/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelFormEdit;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import koneksi.koneksi;
import java.sql.ResultSet;

/**
 *
 * @author Mahayoga
 */
public class pnEditSupplier extends javax.swing.JPanel {
    koneksi db = new koneksi();
    String oldNama;
    private BatalSupplier batalSupplier;
    private EditSupplier editSupplier;
    
    /**
     * Creates new form pnEditSupplier
     */
    public pnEditSupplier(String id) {
        initComponents();
        btnEdit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                theEventEdit();
            }
        });
        btnBatal.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                theEventBatal();
            }
        });
        
        setData(id);
    }
    
    public interface BatalSupplier {
        void batalSupplier();
    }
    public interface EditSupplier {
        void editSupplier();
    }
    
    public void setVariableBatal(BatalSupplier bs) {
        this.batalSupplier = bs;
    }
    public void setVariableEdit(EditSupplier es) {
        this.editSupplier = es;
    }
    
    public void theEventBatal() {
        if(batalSupplier != null) {
            batalSupplier.batalSupplier();
        }
    }
    public void theEventEdit() {
        if(editSupplier != null) {
            editSupplier.editSupplier();
        }
    }
    
    public boolean checkAllForm() {
        if(tfNamaSupplier.getText().equals("") || tfNoTelp.getText().equals("") || tfNamaSupplier.getText().equals("") || tfAlamat.getText().equals("") || tfNamaPerusahaan.getText().equals("") || tfEmail.getText().equals("")) {
            return true;
        }
        return false;
    }
    
    public boolean checkIfIsAlreadyAvailable() {
        if(!tfNamaSupplier.getText().toLowerCase().equals(oldNama)) {
            ResultSet rs = db.ambilData("SELECT * FROM suppliers");
            try {
                while(rs.next()) {
                    if(tfNamaSupplier.getText().toLowerCase().equals(rs.getString("nama_supplier").toLowerCase())) {
                        return true;
                    }
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
        return false;
    }
    
    public boolean checkTheInputIsValid() {
        try {
            Long.parseLong(tfNoTelp.getText());
            if(tfEmail.getText().indexOf("@") == -1) {
                return true;
            }
            return false;
        } catch(Exception e) {
            return true;
        }
    }
    
    public void resetAll() {
        tfKodeSupplier.setText("");
        tfNamaSupplier.setText("");
        tfNoTelp.setText("");
        tfAlamat.setText("");
        tfNamaPerusahaan.setText("");
        tfEmail.setText("");
    }
    
    public void setData(String id) {
        ResultSet rs = db.ambilData("SELECT * FROM suppliers WHERE id_supplier = '" + id + "'");
        try {
            if(rs.next()) {
                this.oldNama = rs.getString("nama_supplier").toLowerCase();
                tfKodeSupplier.setText(rs.getString("id_supplier"));
                tfNamaSupplier.setText(rs.getString("nama_supplier"));
                tfNoTelp.setText(rs.getString("no_telp"));
                tfAlamat.setText(rs.getString("alamat_supplier"));
                tfEmail.setText(rs.getString("email_supplier"));
                tfNamaPerusahaan.setText(rs.getString("asal_perusahaan"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void simpanData() {
        String kd = tfKodeSupplier.getText();
        String nama = tfNamaSupplier.getText();
        String tlp = tfNoTelp.getText();
        String alamat = tfAlamat.getText();
        String email = tfEmail.getText();
        String asal = tfNamaPerusahaan.getText();
        try {
            db.aksi("UPDATE suppliers SET nama_supplier = '" + nama + "', no_telp = '" + tlp + "', alamat_supplier = '" + alamat + "', email_supplier = '" + email + "', asal_perusahaan = '" + asal + "' WHERE id_supplier = '" + kd + "'");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfKodeSupplier = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfNamaSupplier = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfNamaPerusahaan = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfAlamat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfNoTelp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnBatal = new CustomComponent.CustomButton();
        btnEdit = new CustomComponent.CustomButton();

        lbTitle.setBackground(new java.awt.Color(133, 135, 150));
        lbTitle.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(133, 135, 150));
        lbTitle.setText("Edit Data Suppliers");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Kode Supplier");

        tfKodeSupplier.setEnabled(false);
        tfKodeSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKodeSupplierActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Nama Supplier");

        tfNamaSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaSupplierActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Nama Perusahaan");

        tfNamaPerusahaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaPerusahaanActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Email");

        tfAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAlamatActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Alamat");

        tfNoTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNoTelpActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("No Tlp");

        btnBatal.setText("customButton1");
        btnBatal.setBackgroundColor(new java.awt.Color(255, 151, 51));
        btnBatal.setTextColor(java.awt.Color.white);
        btnBatal.setTheText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnEdit.setText("customButton1");
        btnEdit.setBackgroundColor(new java.awt.Color(78, 115, 223));
        btnEdit.setTextColor(java.awt.Color.white);
        btnEdit.setTheText("Edit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(239, 239, 239)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfKodeSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160)
                        .addComponent(tfNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(233, 233, 233)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNamaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNamaPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfAlamat)
                                .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(620, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfKodeSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNamaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfEmail)
                    .addComponent(tfNamaPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(209, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfKodeSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKodeSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKodeSupplierActionPerformed

    private void tfNamaSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaSupplierActionPerformed

    private void tfNamaPerusahaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaPerusahaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaPerusahaanActionPerformed

    private void tfAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAlamatActionPerformed

    private void tfNoTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNoTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNoTelpActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CustomComponent.CustomButton btnBatal;
    private CustomComponent.CustomButton btnEdit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfKodeSupplier;
    private javax.swing.JTextField tfNamaPerusahaan;
    private javax.swing.JTextField tfNamaSupplier;
    private javax.swing.JTextField tfNoTelp;
    // End of variables declaration//GEN-END:variables
}
