/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FormPanel;

import java.util.HashMap;
import koneksi.koneksi;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author rangg
 */
public class pnKeuangan extends javax.swing.JPanel {
    koneksi db = new koneksi();
    HashMap<String, Integer> map = new HashMap<>();
    
    /**
     * Creates new form pnKeuangan
     */
    public pnKeuangan() {
        initComponents();
        setCbTahun();
        String[] blnArr = {"Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember"};
        for(int i = 0; i < blnArr.length; i++) {
            map.put(blnArr[i], i + 1);
        }
    }
    
    public void resetAllForm() {
        cbTahun.setSelectedIndex(0);
        cbBulan.setSelectedIndex(0);
        cbTanggal.setSelectedIndex(0);
        lbKeuanganHarian.setText("");
        lbKeuanganBulanan.setText("");
        lbKeuanganTahunan.setText("");
        lbPengeluaranHarian.setText("");
        lbPengeluaranBulanan.setText("");
        lbPengeluaranTahunan.setText("");
        lbLabaBersih.setText("");
    }
    
    public String changeToNum(String num) {
        String result = "";
        for(int i = 0; i < num.replace('.', 'a').split("a").length; i++) {
            result += num.replace('.', 'a').split("a")[i];
        }
        return result.split("Rp ")[1];
    }
    
    public String changeToRp(String num) {
        NumberFormat nf = NumberFormat.getInstance(new Locale("id", "ID"));
        try {
            return "Rp. " + nf.format(Double.parseDouble(num));
        } catch(Exception e) {
            e.printStackTrace();
        }
        return null;
    }
    
    
    public void setCbTahun() {
        for(int i = 2024; i < 2050; i++) {
            cbTahun.addItem(String.valueOf(i));
        }
    }
    
    public void setCbTgl() {
        HashMap<String, Integer> map = new HashMap<>();
        map.put("Januari", 31);
        map.put("Februari", 28);
        map.put("Maret", 31);
        map.put("April", 30);
        map.put("Mei", 31);
        map.put("Juni", 30);
        map.put("Juli", 31);
        map.put("Agustus", 31);
        map.put("September", 30);
        map.put("Oktober", 31);
        map.put("November", 30);
        map.put("Desember", 31);
        cbTanggal.removeAllItems();
        cbTanggal.addItem("--Tidak dipilih--");
        try {
            if(!cbTahun.getSelectedItem().equals("--Tidak dipilih--") || !cbBulan.getSelectedItem().equals("--Tidak dipilih--")) {
                int kabisat = Integer.parseInt(String.valueOf(cbTahun.getSelectedItem())) % 4;
                if(kabisat == 0 && cbBulan.getSelectedItem().equals("Februari")) {
                    for(int i = 0; i < map.get("Februari") + 1; i++) {
                        cbTanggal.addItem(String.valueOf(i + 1));
                    }
                } else {
                    for(int i = 0; i < map.get(String.valueOf(cbBulan.getSelectedItem())); i++) {
                        cbTanggal.addItem(String.valueOf(i + 1));
                    }
                }
            } else {
                // Hehe
            }
        } catch(Exception e) {
            System.err.println("Masukin dulu bulan atau tahun nya!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbTahun = new javax.swing.JComboBox<>();
        cbBulan = new javax.swing.JComboBox<>();
        cbTanggal = new javax.swing.JComboBox<>();
        customPanel1 = new CustomComponent.CustomPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        lbKeuanganHarian = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        customPanel4 = new CustomComponent.CustomPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        lbKeuanganBulanan = new javax.swing.JLabel();
        customPanel5 = new CustomComponent.CustomPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        lbKeuanganTahunan = new javax.swing.JLabel();
        customPanel7 = new CustomComponent.CustomPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        lbPengeluaranBulanan = new javax.swing.JLabel();
        customPanel6 = new CustomComponent.CustomPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        lbPengeluaranHarian = new javax.swing.JLabel();
        customPanel8 = new CustomComponent.CustomPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        lbPengeluaranTahunan = new javax.swing.JLabel();
        customPanel9 = new CustomComponent.CustomPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        lbLabaBersih = new javax.swing.JLabel();
        btnCek = new CustomComponent.CustomButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitle.setBackground(new java.awt.Color(133, 135, 150));
        lbTitle.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(133, 135, 150));
        lbTitle.setText("Data Keuangan");
        add(lbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 370, 33));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Tahun");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Bulan");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 60, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Tanggal");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        cbTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Tidak dipilih--" }));
        cbTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTahunActionPerformed(evt);
            }
        });
        add(cbTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 130, 30));

        cbBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Tidak dipilih--", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        cbBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBulanActionPerformed(evt);
            }
        });
        add(cbBulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 130, 30));

        cbTanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Tidak dipilih--" }));
        add(cbTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 130, 30));

        customPanel1.setBackground(new java.awt.Color(78, 115, 223));
        customPanel1.setBackgroundColor(new java.awt.Color(78, 115, 223));
        customPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Keuangan Harian");
        customPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 220, 40));

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel24.setForeground(new java.awt.Color(255, 255, 255));

        lbKeuanganHarian.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbKeuanganHarian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbKeuanganHarian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbKeuanganHarian, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        customPanel1.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, 220, -1));

        add(customPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 220, 140));

        jLabel1.setText("*Cari Berdasarkan Kebutuhan*");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 30));

        customPanel4.setBackground(new java.awt.Color(78, 115, 223));
        customPanel4.setBackgroundColor(new java.awt.Color(78, 115, 223));
        customPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Keuangan Bulanan");
        customPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 220, 40));

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel27.setForeground(new java.awt.Color(255, 255, 255));

        lbKeuanganBulanan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbKeuanganBulanan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbKeuanganBulanan, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbKeuanganBulanan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        customPanel4.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, 220, 100));

        add(customPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 220, -1));

        customPanel5.setBackground(new java.awt.Color(78, 115, 223));
        customPanel5.setBackgroundColor(new java.awt.Color(78, 115, 223));
        customPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Keuangan Tahunan");
        customPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 230, 50));

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));
        jPanel28.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel28.setForeground(new java.awt.Color(255, 255, 255));

        lbKeuanganTahunan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbKeuanganTahunan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbKeuanganTahunan, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbKeuanganTahunan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        customPanel5.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, 220, 100));

        add(customPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 220, -1));

        customPanel7.setBackground(new java.awt.Color(78, 115, 223));
        customPanel7.setBackgroundColor(new java.awt.Color(78, 115, 223));
        customPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Pengeluaran Bulanan");
        customPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 220, 40));

        jPanel30.setBackground(new java.awt.Color(255, 255, 255));
        jPanel30.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel30.setForeground(new java.awt.Color(255, 255, 255));

        lbPengeluaranBulanan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbPengeluaranBulanan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPengeluaranBulanan, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbPengeluaranBulanan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        customPanel7.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, 220, 98));

        add(customPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 220, 140));

        customPanel6.setBackground(new java.awt.Color(78, 115, 223));
        customPanel6.setBackgroundColor(new java.awt.Color(78, 115, 223));
        customPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Pengeluaran Harian");
        customPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 40));

        jPanel29.setBackground(new java.awt.Color(255, 255, 255));
        jPanel29.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel29.setForeground(new java.awt.Color(255, 255, 255));

        lbPengeluaranHarian.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbPengeluaranHarian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPengeluaranHarian, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbPengeluaranHarian, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        customPanel6.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, 220, 98));

        add(customPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 220, 140));

        customPanel8.setBackground(new java.awt.Color(78, 115, 223));
        customPanel8.setBackgroundColor(new java.awt.Color(78, 115, 223));
        customPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Pengeluaran Tahunan");
        customPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 40));

        jPanel31.setBackground(new java.awt.Color(255, 255, 255));
        jPanel31.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel31.setForeground(new java.awt.Color(255, 255, 255));

        lbPengeluaranTahunan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbPengeluaranTahunan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPengeluaranTahunan, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbPengeluaranTahunan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        customPanel8.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, 220, 98));

        add(customPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 220, 140));

        customPanel9.setBackground(new java.awt.Color(78, 115, 223));
        customPanel9.setBackgroundColor(new java.awt.Color(78, 115, 223));
        customPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Total Laba Bersih");
        customPanel9.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 220, 40));

        jPanel32.setBackground(new java.awt.Color(255, 255, 255));
        jPanel32.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel32.setForeground(new java.awt.Color(255, 255, 255));

        lbLabaBersih.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbLabaBersih.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbLabaBersih, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbLabaBersih, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        customPanel9.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, 220, 100));

        add(customPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, 220, -1));

        btnCek.setText("customButton1");
        btnCek.setBackgroundColor(new java.awt.Color(255, 151, 51));
        btnCek.setTextBold(0);
        btnCek.setTextColor(java.awt.Color.white);
        btnCek.setTheText("Cek!");
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });
        add(btnCek, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 90, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void cbTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTahunActionPerformed
        // TODO add your handling code here:
        setCbTgl();
    }//GEN-LAST:event_cbTahunActionPerformed

    private void cbBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBulanActionPerformed
        // TODO add your handling code here:
        setCbTgl();
    }//GEN-LAST:event_cbBulanActionPerformed

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
         // TODO add your handling code here:
        String tgl = cbTanggal.getSelectedItem().toString();
        String bln = cbBulan.getSelectedItem().toString();
        String thn = cbTahun.getSelectedItem().toString();
        ResultSet pemasukanHarian = db.ambilData("SELECT SUM(harga_total) AS hehe FROM transaksi WHERE tanggal_transaksi = '" + thn + "-" + map.get(bln) + "-" + tgl + "'");
        ResultSet pemasukanBulanan = db.ambilData("SELECT SUM(harga_total) AS hehe FROM transaksi WHERE tanggal_transaksi >= '" + thn + "-" + map.get(bln) + "-01' AND tanggal_transaksi <= '" + thn + "-" + map.get(bln) + "-31'");
        ResultSet pemasukanTahunan = db.ambilData("SELECT SUM(harga_total) AS hehe FROM transaksi WHERE tanggal_transaksi >= '" + thn + "-01-01' AND tanggal_transaksi <= '" + thn + "-12-31'");
        
        ResultSet pengeluaranHarian = db.ambilData("SELECT SUM(harga) AS hehe FROM pengeluaran WHERE tanggal_pengeluaran = '" + thn + "-" + map.get(bln) + "-" + tgl + "'");
        ResultSet pengeluaranBulanan = db.ambilData("SELECT SUM(harga) AS hehe FROM pengeluaran WHERE tanggal_pengeluaran >= '" + thn + "-" + map.get(bln) + "-01' AND tanggal_pengeluaran <= '" + thn + "-" + map.get(bln) + "-31'");
        ResultSet pengeluaranTahunan = db.ambilData("SELECT SUM(harga) AS hehe FROM pengeluaran WHERE tanggal_pengeluaran >= '" + thn + "-01-01' AND tanggal_pengeluaran <= '" + thn + "-12-31'");
        
        ResultSet labaBulanBersih = db.ambilData("SELECT dt.kode_barang, SUM(dt.harga_total) - SUM((sb.harga_jual * dt.jumlah_barang)) AS hehe FROM detail_transaksi dt INNER JOIN stok_barang sb ON dt.kode_barang = sb.id_barang WHERE dt.tanggal >= '" + thn + "-" + map.get(bln) +"-01' AND dt.tanggal <= '" + thn + "-" + map.get(bln) +"-31' GROUP BY dt.kode_barang;");
        double totalLaba = 0;
        try {
            pemasukanHarian.next();
            pemasukanBulanan.next();
            pemasukanTahunan.next();
            pengeluaranHarian.next();
            pengeluaranBulanan.next();
            pengeluaranTahunan.next();
            while(labaBulanBersih.next()) {
                totalLaba += Double.parseDouble(labaBulanBersih.getString("hehe"));
            }
            lbLabaBersih.setText(changeToRp(String.valueOf(totalLaba)));
            
            if(pemasukanHarian.getString("hehe") != null) {
                lbKeuanganHarian.setText(changeToRp(pemasukanHarian.getString("hehe")));
            } else {
                lbKeuanganHarian.setText("Tidak ada Data!");
            }
            if(pemasukanBulanan.getString("hehe") != null) {
                lbKeuanganBulanan.setText(changeToRp(pemasukanBulanan.getString("hehe")));
            } else {
                lbKeuanganBulanan.setText("Tidak ada Data!");
            }
            if(pemasukanTahunan.getString("hehe") != null) {
                lbKeuanganTahunan.setText(changeToRp(pemasukanTahunan.getString("hehe")));
            } else {
                lbKeuanganTahunan.setText("Tidak ada Data!");
            }
            
            if(pengeluaranHarian.getString("hehe") != null) {
                lbPengeluaranHarian.setText(changeToRp(pengeluaranHarian.getString("hehe")));
            } else {
                System.out.println("Heheheehhehehehehe");
                lbPengeluaranHarian.setText("Tidak ada Data!");
            }
            if(pengeluaranBulanan.getString("hehe") != null) {
                lbPengeluaranBulanan.setText(changeToRp(pengeluaranBulanan.getString("hehe")));
            } else {
                lbPengeluaranBulanan.setText("Tidak ada Data!");
            }
            if(pengeluaranTahunan.getString("hehe") != null) {
                lbPengeluaranTahunan.setText(changeToRp(pengeluaranTahunan.getString("hehe")));
            } else {
                lbPengeluaranTahunan.setText("Tidak ada Data!");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnCekActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CustomComponent.CustomButton btnCek;
    private javax.swing.JComboBox<String> cbBulan;
    private javax.swing.JComboBox<String> cbTahun;
    private javax.swing.JComboBox<String> cbTanggal;
    private CustomComponent.CustomPanel customPanel1;
    private CustomComponent.CustomPanel customPanel4;
    private CustomComponent.CustomPanel customPanel5;
    private CustomComponent.CustomPanel customPanel6;
    private CustomComponent.CustomPanel customPanel7;
    private CustomComponent.CustomPanel customPanel8;
    private CustomComponent.CustomPanel customPanel9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JLabel lbKeuanganBulanan;
    private javax.swing.JLabel lbKeuanganHarian;
    private javax.swing.JLabel lbKeuanganTahunan;
    private javax.swing.JLabel lbLabaBersih;
    private javax.swing.JLabel lbPengeluaranBulanan;
    private javax.swing.JLabel lbPengeluaranHarian;
    private javax.swing.JLabel lbPengeluaranTahunan;
    private javax.swing.JLabel lbTitle;
    // End of variables declaration//GEN-END:variables
}
