/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelFormTambah;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import koneksi.koneksi;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.util.HashMap;

/**
 *
 * @author Mahayoga
 */
public class pnTambahKeuangan extends javax.swing.JPanel {
    koneksi db = new koneksi();
    private BatalKeuangan batalBarang;
    private SimpanKeuangan simpanBarang;

    /**
     * Creates new form pnTambahBarang
     */
    public pnTambahKeuangan() {
        initComponents();
        checkId();
        getTheDate();
        btnSimpan.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                theEventSimpan();
            }
        });
        btnBatal.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                theEventBatal();
            }
        });
    }
    
    public interface BatalKeuangan {
        void batalKeuangan();
    }
    public interface SimpanKeuangan {
        void simpanKeuangan();
    }
    
    public void setVariableBatal(BatalKeuangan bs) {
        this.batalBarang = bs;
    }
    public void setVariableSimpan(SimpanKeuangan es) {
        this.simpanBarang = es;
    }
    
    public void theEventBatal() {
        if(batalBarang != null) {
            batalBarang.batalKeuangan();
        }
    }
    public void theEventSimpan() {
        if(simpanBarang != null) {
            simpanBarang.simpanKeuangan();
        }
    }
    
    public boolean checkAllForm() {
        if(tfKodePengeluaran.getText().equals("") || tfTanggalPengeluaran.getText().equals("") || cbJenisPengeluaran.getSelectedItem().toString().equals("--Tidak dipilih--") || tfHarga.getText().equals("") || taKeterangan.getText().equals("")) {
            return true;
        }
        return false;
    }
    
    public boolean checkTheInputIsValid() {
        try {
            Integer.parseInt(tfHarga.getText());
            return false;
        } catch(Exception e) {
            return true;
        }
    }
    
    public void resetAll() {
        getTheDate();
        cbJenisPengeluaran.setSelectedIndex(0);
        tfHarga.setText("");
        taKeterangan.setText("");
    }
    
    public void getTheDate() {
        tfTanggalPengeluaran.setText(LocalDate.now().toString());
    }
    
    public void checkId() {
        ResultSet rs = db.ambilData("SELECT * FROM pengeluaran ORDER BY kode_pengeluaran DESC");
        try {
            if(rs.next()) {
                int id = Integer.parseInt(rs.getString("kode_pengeluaran").substring(2, 6)); //KP0001 
                id++;
                if(id <= 9) {
                    tfKodePengeluaran.setText(rs.getString("kode_pengeluaran").substring(0, 2) + "000" + id);
                } else if(id <= 99) {
                    tfKodePengeluaran.setText(rs.getString("kode_pengeluaran").substring(0, 2) + "00" + id);
                } else if(id <= 999) {
                    tfKodePengeluaran.setText(rs.getString("kode_pengeluaran").substring(0, 2) + "0" + id);
                } else if(id <= 9999) {
                    tfKodePengeluaran.setText(rs.getString("kode_pengeluaran").substring(0, 2) + "" + id);
                }
            } else {
                tfKodePengeluaran.setText(rs.getString("kode_pengeluaran").substring(0, 2) + "0001");
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
    
    public void simpanData() {
//      kode_pengeluaran
//	tanggal_pengeluara
//	jenis_pengeluaran
//	harga
//	keterangan
        String kd = tfKodePengeluaran.getText();
        String tgl = tfTanggalPengeluaran.getText();
        String jenis = String.valueOf(cbJenisPengeluaran.getSelectedItem());
        String harga = tfHarga.getText();
        String keterangan = taKeterangan.getText();
        try {
            db.aksi("INSERT INTO pengeluaran VALUES ('" + kd + "', '" + tgl + "', '" + jenis + "', '" + harga + "', '" + keterangan + "')");
        } catch(Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        tfKodePengeluaran = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfTanggalPengeluaran = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfHarga = new javax.swing.JTextField();
        lbTitle = new javax.swing.JLabel();
        cbJenisPengeluaran = new javax.swing.JComboBox<>();
        btnBatal = new CustomComponent.CustomButton();
        btnSimpan = new CustomComponent.CustomButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taKeterangan = new javax.swing.JTextArea();

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Kode Pengeluaran ");

        tfKodePengeluaran.setEnabled(false);
        tfKodePengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKodePengeluaranActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Jenis Pengeluaran");

        tfTanggalPengeluaran.setEnabled(false);
        tfTanggalPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTanggalPengeluaranActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Harga");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Keterangan");

        tfHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHargaActionPerformed(evt);
            }
        });

        lbTitle.setBackground(new java.awt.Color(133, 135, 150));
        lbTitle.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(133, 135, 150));
        lbTitle.setText("Tambah Data Pengeluaran");

        cbJenisPengeluaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Tidak dipilih--", "Operasional", "Beli Barang", "Gaji Karyawan", "Lainnya" }));
        cbJenisPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJenisPengeluaranActionPerformed(evt);
            }
        });

        btnBatal.setText("customButton1");
        btnBatal.setBackgroundColor(new java.awt.Color(255, 151, 51));
        btnBatal.setTextColor(java.awt.Color.white);
        btnBatal.setTheText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnSimpan.setText("customButton1");
        btnSimpan.setBackgroundColor(new java.awt.Color(78, 115, 223));
        btnSimpan.setTextColor(java.awt.Color.white);
        btnSimpan.setTheText("Simpan");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Tanggal Pengeluaran");

        taKeterangan.setColumns(20);
        taKeterangan.setRows(5);
        jScrollPane1.setViewportView(taKeterangan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfKodePengeluaran))
                            .addComponent(jLabel7)
                            .addComponent(cbJenisPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfTanggalPengeluaran)
                            .addComponent(tfHarga)))
                    .addComponent(lbTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(833, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(15, 15, 15)
                        .addComponent(tfKodePengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(cbJenisPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(tfTanggalPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(10, 10, 10)
                        .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfKodePengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKodePengeluaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKodePengeluaranActionPerformed

    private void tfTanggalPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTanggalPengeluaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTanggalPengeluaranActionPerformed

    private void tfHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHargaActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalActionPerformed

    private void cbJenisPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisPengeluaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJenisPengeluaranActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CustomComponent.CustomButton btnBatal;
    private CustomComponent.CustomButton btnSimpan;
    private javax.swing.JComboBox<String> cbJenisPengeluaran;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JTextArea taKeterangan;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfKodePengeluaran;
    private javax.swing.JTextField tfTanggalPengeluaran;
    // End of variables declaration//GEN-END:variables
}
